### PR TITLE
Add install instructions to the readme

### PR DESCRIPTION
**Pull request by marc-gr**

### CODE REVIEW

**Comment by xsb** [comment]
I'd omit the manual install instructions and simply provide them for macOS and go get. And probably not more than one way of doing it in mac, to keep the README short.

**Comment by marc-gr** [comment]
Makes more sense now?

**Comment by xsb** [comment]
@marc-gr I like it!

Some minor changes if you want:
- s/OSX/macOS/
- s/a simple:/you can use:/

**Comment by xsb** [comment]
I made the changes myself, going to merge now

**Pull request merged**
